import { Geist, Geist_Mono, Nunito, Roboto } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const nunito = Nunito({
    weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],

    variable: "--font-nunito",
    subsets: ["latin"],
});

const roboto = Roboto({
    weight: ["100", "300", "400", "700"],
    variable: "--font-roboto",
    subsets: ["latin"],
});

export const metadata = {
    title: "Booking App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${nunito.className} text-pretty `}>
                {children}
            </body>
        </html>
    );
}
